server:
  port: 80
spring:
  redis:
    host: 192.168.253.88
    password: 825119
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"  #允许所有ip跨域访问
            allowedMethods: "*"  #允许所有请求方式
            allowedHeaders: "*"  #允许任何头进行跨域
            allowCredentials: true #允许携带cookie
            ## 以上配完成，简单跨域复杂跨域都允许。

      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**
        - id: lb_test
          uri: lb://service-item
          predicates:
            - Path=/redis/incr
        - id: user_roote
          uri: lb://service-user
          predicates:
            - Path=/api/user/**

        - id: web-all
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com,gmall.com


