server:
  port: 7000  #每种微服务用一个整数端口  7000~7100

spring:
  datasource:
    url: jdbc:mysql://192.168.253.88:3306/gmall_product?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#mybatis-plus:
#  #xml文件位置
#  mapper-locations: classpath:com/atguigu/gmall/product/mapper/**/*.xml


    #mybatis-plus
    #mybatis-plus:
    #  mapper-locations: classpath*:/mapper/**/*.xml